site_name: Projeto estrtura de dados do zero
theme:
  name: bootstrap386
  palette:  
    primary: deep blue
  language: pt

repo_name: "Rafael07/projeto_0123"
repo_url: "https://github.com/Rafael07/projeto_0123"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python
nav:
  - Home: index.md
  - API: api.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python